### ISSUE TITLE
suggestion: writing on signs

### ISSUE THREAD

**Issue by XxN4BxX** [Darkhax-Minecraft/Runelic#1]
would it be possible to have a way to write on signs? like a symbol before text would write in runelic instead of normal text
E.G
"#text"

**Comment by Darkhax** [comment]
Hello, this is a great suggestion but unfortunately it's not realistic to add with how signs currently work. There is a command available to admins which allow them to "encode" a sign with the font however that's not useful for survival mode. The mod [DarkUtilities](https://www.curseforge.com/minecraft/mc-mods/dark-utilities) has an item called the Runelic Tome which can be used to rename items with the font, maybe I could make an update which allows the book to work on signs as well?

**Comment by itsdinkd** [comment]
what is the point of this mod? you can't read the font I don't understand

**Comment by Darkhax** [comment]
@red2blue The font is a simple substitution for the English alphabet. Anyone is able to read it, even without a key/legend if they are willing to put some time and thought into it. The mod is intended to be used as an alternative font in other mods, modpacks, and adventure maps that want to have magical text/glyphs but don't want to use the Standard Galactic Alphabet font.
