### ISSUE TITLE
[1.19.2] Rune banner patterns only show from the front

### ISSUE THREAD

**Issue by Illios42** [Darkhax-Minecraft/Runelic#10]
Heya so I am using the latest 1.19.2 version of Runelic for forge and the banner patterns are only visible from the front, not the back. Vanilla behavior would be to show both sides and it's a bit annoying when using them since I use a mod that allows hanging banners from the roof, making the missing pattern wildly obvious.

**Comment by Darkhax** [comment]
Thanks for letting me know. I decided against doing the back because there are so many symbols and mirroring the design on the back adds a lot of work. In vanilla the back textures are pretty useless but your use case is valid. I will work on correcting this when I have time.

**Comment by Darkhax** [comment]
Hello, this issue has been fixed in 14.1.4 for [Forge](https://www.curseforge.com/minecraft/mc-mods/runelic/files/4337495) and [Fabric](https://www.curseforge.com/minecraft/mc-mods/runelic/files/4337494). Sorry for taking so long to get to this.
