### ISSUE TITLE
Commands not appearing

### ISSUE THREAD

**Issue by SkytheAlicorn** [Darkhax-Minecraft/Runelic#13]
I installed the mod into my 1.19.4 pack but the commands won't appear no matter what I do

**Comment by Darkhax** [comment]
Hello, sorry for the confusion. These commands were moved to the Bookshelf mod so you can use any font. `/bookshelf font`. It has all of the same functionality but you can use it for all fonts not just ours.

**Comment by SkytheAlicorn** [comment]
Thank you
This will help a lot.
