### ISSUE TITLE
More fonts?

### ISSUE THREAD

**Issue by SurgeXs** [Darkhax-Minecraft/Runelic#15]
Could you add the enchanting table language and the illageralt language?  If not to this mod, then possibly as standalone mods?  Ideally with banner patterns btw.

**Comment by Darkhax** [comment]
Hello, Mojang already includes those fonts in the game and they are compatible with the commands used by this mod. The IDs are `minecraft:alt` and `minecraft:illageralt`. I have plans to release banners of the other vanilla fonts and my other font mods soon, however I am focusing on 1.20/1.120.1 ports right now.
