### ISSUE TITLE
Feature Request: Config/Language option to make EVERYTHING runelic

### ISSUE THREAD

**Issue by AzureMonument** [Darkhax-Minecraft/Runelic#4]
So I've recently come up with a bad idea that I would _really_ like to have. I want everything to replaced with runelic by default- basically treating it as a language setting if possible. I don't even know how difficult this would be to implement, but I would love to play with it.

**Comment by Darkhax** [comment]
Unfortunately there is nothing built in to allow this, Minecraft's system just isn't set up to allow this. There are some ways to hack it in, but I am not too keen on doing that.
