### ISSUE TITLE
[Suggestion] Separate the fabric version from forge version on curseforge 

### ISSUE THREAD

**Issue by starmun-0010** [Darkhax-Minecraft/Runelic#5]
The way curseforge lists mod files, it becomes really hard to update mods which have mixed fabric and forge files.
More often than not, the end user ends up installing the wrong platform binaries.
Please upload them to separate projects.

![image](https://user-images.githubusercontent.com/5557278/115316322-94485e80-a192-11eb-8792-baedd2aafd10.png)

**Comment by RepoDraghon** [comment]
I second this!

**Comment by Darkhax** [comment]
The CurseForge team has released an update which should avoid this issue entirely. Those using the old version of their launcher can avoid this by excluding beta files from packs in their settings (this is the default behavior).
